spring:
  profiles:
    active: dev
    # dev 就会读取application-dev.yml文件
    # prod 就会读取application-dev.yml文件
  jpa:
    hibernate:
      ddl-auto: none
      # update #不会删除表
      # create-drop #将表数据清空后再创建表 测试时比较有用
      # none 禁止生成表,设置后，就不会项目启动后就不会创建表了
  jackson:
    property-naming-strategy: SNAKE_CASE #所有返回前端的字段都已下划线的形式返回
    serialization: #时间全部以时间戳的形式返回
      WRITE_DATES_AS_TIMESTAMPS: true


#controller的根包
whj:
  api-package: com.whj.springbootcode.api